# Generated by Django 4.1.5 on 2023-01-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='head_word_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='vocabulary_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
