# Generated by Django 4.1.5 on 2023-01-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_text_head_word_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('name_en_us', models.CharField(max_length=48, null=True)),
                ('name_hi', models.CharField(max_length=48, null=True)),
                ('local_name', models.CharField(max_length=48)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
