# Generated by Django 4.1.5 on 2023-01-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_word_text_language_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.language'),
            preserve_default=False,
        ),
    ]
