# Generated by Django 4.1.5 on 2023-01-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_word_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('phrase', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
            ],
        ),
        migrations.RemoveField(
            model_name='term',
            name='word',
        ),
        migrations.DeleteModel(
            name='word',
        ),
        migrations.AddField(
            model_name='term',
            name='string',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.string'),
            preserve_default=False,
        ),
    ]
