# Generated by Django 4.1.5 on 2023-01-28 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='from_string',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='to_string',
        ),
        migrations.AddField(
            model_name='translation',
            name='source_string',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_string', to='core.string'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='target_string',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_string', to='core.string'),
            preserve_default=False,
        ),
    ]
