# Generated by Django 4.1.5 on 2023-01-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_translation_from_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='translations',
            field=models.ManyToManyField(through='core.Translation', to='core.string'),
        ),
    ]
